Contactini/Controllers/UsersAdminController.cs
using IdentitySample.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Contactini.Models.Entities;
using Contactini.DAL;
using Contactini.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System;

namespace IdentitySample.Controllers
{
    // Controller responsible for operations on users profiles exactly on the ApplicationUserModel
   // [Authorize(Roles = "Admin")]
    public class UsersAdminController : Controller
    {
        public UsersAdminController()
        {
        }
        ContactiniContext ctx = new ContactiniContext();
        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }
        // Our way to access the AplicationUser Model and apply modifications ( delete , create , edit ...)
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        
        /// <summary>
        /// Show all the users of our application
        /// </summary>
        /// <returns></returns>
        // GET: /Users/
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            ViewBag.photoLink = await getPicLink();
            return View(await UserManager.Users.ToListAsync());
        }

        /// <summary>
        /// Afficher les détails d'un utilisateur spécifique
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: /Users/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);
            ViewBag.photoLink = await getPicLink();
            return View(user);
        }

        /// <summary>
        /// The next method provide the process to create a user  manually ! but in this app we're not using it , since evry user should go through the registration process 
        /// specified in the account controller in order to have an account
        /// </summary>
        /// <returns></returns>
        // GET: /Users/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            if(User.IsInRole("Admin"))
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            ViewBag.photoLink = await getPicLink();
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser {
                    UserName = userViewModel.Email,
                    FullName = userViewModel.FullName,
                    Email = userViewModel.Email,
                    // Add the Address Info:
                    StreetAddress = userViewModel.StreetAddress,
                    City = userViewModel.City,
                    State = userViewModel.State,
                    PostalCode = userViewModel.PostalCode
                };
                // Add the Address Info:
                //user.StreetAddress = userViewModel.StreetAddress;
                //user.City = userViewModel.City;
                //user.State = userViewModel.State;
                //user.PostalCode = userViewModel.PostalCode;
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        /// <summary>
        /// Edit is the method the admin use in order to modify a user access level , so to give him new access or remove his access to some
        /// space of the app ( for example allow admin access and remove Service provider Access)
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: /Users/Edit/1
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);
            ViewBag.photoLink = await getPicLink();
            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                FullName = user.FullName,
                // Include the Addresss info:
                UserName = user.UserName,
                StreetAddress = user.StreetAddress,
                City = user.City,
                State = user.State,
                PostalCode = user.PostalCode,
                PhotoLink = user.PhotoLink,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,FullName,UserName,Id,StreetAddress,City,State,PostalCode,photoLink")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                user.FullName = editUser.FullName;
                user.UserName = editUser.UserName;
                user.Email = editUser.Email;
                user.StreetAddress = editUser.StreetAddress;
                user.City = editUser.City;
                user.State = editUser.State;
                user.PostalCode = editUser.PostalCode;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }
        /// <summary>
        /// This is the metod used by any user tp update his profile data ( fullsName , username ,address , profile pic....)
        /// </summary>
        /// <param name="id"></param>
        /// <param name="returnUrl"></param>
        /// <returns></returns>
        [Authorize]
        [HttpGet]
        public async Task<ActionResult> _Edit (string id,string returnUrl)
        {
            if (String.IsNullOrEmpty(returnUrl)
                 && Request.UrlReferrer != null
                 && Request.UrlReferrer.ToString().Length > 0)
            {
                return RedirectToAction("_Edit", new { returnUrl = Request.UrlReferrer.ToString() });
            }


            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

Contactini/Views/UsersAdmin/Create.cshtml
@model IdentitySample.Models.RegisterViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new account.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-error" })
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.FullName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FullName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.Address, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.City, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.State, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.State, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.PostalCode, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PostalCode, new { @class = "form-control" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-2 control-label">
            Select User Role
        </label>
        <div class="col-md-10">
            @foreach (var item in (SelectList)ViewBag.RoleId)
            {
                <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" />
                @Html.Label(item.Value, new { @class = "control-label" })
            }
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Contactini/Views/UsersAdmin/Delete.cshtml
@model IdentitySample.Models.ApplicationUser

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<h2 class="well text-center">Supprimer cet utilisateur.</h2>

<h3>Etes vous sure de supprimer cet utilisateur?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Nom d'utilisateur")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt>
            @Html.DisplayName("Nom et prénom")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt>
            @Html.DisplayName("Addresse")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DisplayAddress)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-trash"></span>Supprimer </button> |
        <a class="btn btn-primary" href="@Url.Action("Index","UsersAdmin")"><span class="glyphicon glyphicon-backward"></span> Retour</a>
    </div>
    }
</div>

Contactini/Views/UsersAdmin/Details.cshtml
@model IdentitySample.Models.ApplicationUser

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<h2 class="well text-center">Details d'utilisateurs .</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Nom d'utilisateur")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt>
            @Html.DisplayName("Nom et prénom")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt>
            @Html.DisplayName("Addresse")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DisplayAddress)
        </dd>
        <dt>
            @Html.DisplayName("Email")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<h4 class="well text-center">Roles de cet utilisateur</h4>
@if (ViewBag.RoleNames.Count == 0)
{
    <hr />
    <p>Cette Utilisateur n'a aucune role.</p>
}

<table class="table">

    @foreach (var item in ViewBag.RoleNames)
    {
        <tr>
            <td align="center">
                @item
            </td>
        </tr>
    }
</table>
<div align="center">
    <a href="@Url.Action("Edit","UsersAdmin", new { id = Model.Id })" class="btn btn-primary"><span class="glyphicon glyphicon-edit"></span> Modifier </a>
    <a href="@Url.Action("Index","UsersAdmin")" class="btn btn-primary"><span class="glyphicon glyphicon-backward"></span> Retour </a>

    </div>

Contactini/Views/UsersAdmin/Edit.cshtml
@model IdentitySample.Models.EditUserViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<h2 class="well text-center">Allocation des roles</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)

    <div class="form-group" hidden="hidden">
        @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Email)
        </div>
    </div>
    <div class="form-group" hidden="hidden">
        @Html.LabelFor(model => model.FullName, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.FullName, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.FullName)
        </div>
    </div>
    <div class="form-group" hidden="hidden">
        @Html.LabelFor(model => model.UserName, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UserName)
        </div>
    </div>
    <div class="form-group" hidden="hidden">
        @Html.LabelFor(model => model.StreetAddress, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.StreetAddress, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group" hidden="hidden">
        @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.City, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group" hidden="hidden">
        @Html.LabelFor(model => model.State, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.State, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group" hidden="hidden">
        @Html.LabelFor(model => model.PostalCode, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PostalCode, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group" hidden="hidden">
        @Html.LabelFor(model => model.PhotoLink, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.PhotoLink, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group" >
        @Html.Label("Roles", new { @class = "control-label col-md-2" })
        <span class=" col-md-10">
            @foreach (var item in Model.RolesList)
            {
                <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                @Html.Label(item.Value, new { @class = "control-label" })
            }
        </span>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Enregistrer" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    <a class="btn btn-primary" href="@Url.Action("Index","UsersAdmin")"><span class="glyphicon glyphicon-backward"></span> Retour</a>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Contactini/Views/UsersAdmin/Index.cshtml
@model IEnumerable<IdentitySample.Models.ApplicationUser>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2 class="well text-center">Liste d'utilisateurs</h2>

@*<p>
    <a href="@Url.Action("Nouveau","Create")" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus"></span>Nouveau
    </a>
</p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Nom d'Utilisateurs")
        </th>
        <th>
            @Html.DisplayName("Addresse Email")
        </th>
        <th>

        </th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.Id })*@

            <a href="@Url.Action("Edit","UsersAdmin", new { id = item.Id })" class="btn btn-primary">
                <span class="glyphicon glyphicon-edit"></span>Modifier
            </a>
            <a href="@Url.Action("Details","UsersAdmin", new { id = item.Id })" class="btn btn-primary">
                <span class="glyphicon glyphicon-sunglasses"></span>Détails
            </a>
            <a href="@Url.Action("Delete","UsersAdmin", new { id = item.Id })" class="btn btn-primary">
                <span class="glyphicon glyphicon-trash"></span>Supprimer
            </a>
            <a href="@Url.Action("Block","UsersAdmin", new { id = item.Id })" class="btn btn-primary">
                <span class="glyphicon glyphicon-ban-circle"></span>Block
            </a>
        </td>
    </tr>
    }

</table>

Contactini/Views/UsersAdmin/Sta1.cshtml
@{
    ViewBag.Title = "Statistics";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<style>
    body {
        background-color: white !important;
    }
</style>

<div>
    <h2 class="well text-center">Statistiques</h2>

    <div id="chartContainer"></div>
    <div>
        <a href="@Url.Action("Sta2","UsersAdmin")" class="btn btn-primary"><span class="glyphicon glyphicon-backward"></span>Précédent</a>
        <a href="@Url.Action("statistics","UsersAdmin")" class="btn btn-primary pull-right">Suivant<span class="glyphicon glyphicon-forward"></span></a>
    </div>
    <div id="StatesChartContainer"></div>
    <div id="PiechartContainer"></div>
</div>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
<script type="text/javascript">
    var result = @Html.Raw(ViewBag.lista);
	var dataPoints =[];
	for(var i = 0; i < result.length; i++){
        dataPoints.push({ label: result[i].stateName, legendText: result[i].stateName, y: result[i].MissionsCount});
    }
  

    
      

         window.onload = function () {
            var chart2 = new CanvasJS.Chart("StatesChartContainer", {
                title: {
                    text: "Offre Par Governorat"
                },
                animationEnabled: true,
                legend: {
                    fontSize: 20,
                    fontFamily: "Helvetica"
                },
                theme: "theme2",
                data: [
                {
                    type: "doughnut",
                    indexLabelFontFamily: "Garamond",
                    indexLabelFontSize: 20,
                    indexLabel: "{label} {y}%",
                    startAngle: -20,
                    showInLegend: true,
                    toolTipContent: "{legendText} {y}%",
                  
                    dataPoints: dataPoints

                }
                ]
            });
        chart2.render();
        };
</script>

Contactini/Views/UsersAdmin/Sta2.cshtml
@{
    ViewBag.Title = "Statistics";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<style>
    body {
        background-color: white !important;
    }
</style>

<div>
    <h2 class="well text-center">Statistiques</h2>
    <div>
        <a href="@Url.Action("Statistics","UsersAdmin")" class="btn btn-primary"><span class="glyphicon glyphicon-backward"></span>Précédent</a>
        <a href="@Url.Action("sta1","UsersAdmin")" class="btn btn-primary pull-right">Suivant<span class="glyphicon glyphicon-forward"></span></a>
    </div>
    <div id="PiechartContainer"></div>
</div>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
<script type="text/javascript">

    var result1 = @Html.Raw(ViewBag.list);
	var data =[];
	for(var i = 0; i < result1.length; i++){
        data.push({ label: result1[i].domainName, legendText:result1[i].domainName, y: result1[i].MissionsCount});
    }

    window.onload = function () {
        var chart3 = new CanvasJS.Chart("PiechartContainer", {
            title: {
                text: "Offres par Domaines"
            },
            animationEnabled: true,
            legend: {
                verticalAlign: "center",
                horizontalAlign: "left",
                fontSize: 20,
                fontFamily: "Helvetica"
            },
            theme: "theme2",
            data: [
                {
                    type: "pie",
                    indexLabelFontFamily: "Garamond",
                    indexLabelFontSize: 20,
                    indexLabel: "{label} {y}%",
                    startAngle: -20,
                    showInLegend: true,
                    toolTipContent: "{legendText} {y}%",
                    dataPoints:data
                }
            ]
        });

        chart3.render();
        };
</script>

Contactini/Views/UsersAdmin/Statistics.cshtml
@{
    ViewBag.Title = "Statistics";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<style>
    body{
        background-color:white !important;
    }
</style>

<div>
    <h2 class="well text-center">Statistiques</h2>
    <div class="row">
        <a href="@Url.Action("sta1","UsersAdmin")" class="btn btn-primary"><span class="glyphicon glyphicon-backward"></span>Précédant</a>
        <a href="@Url.Action("sta2","UsersAdmin")" class="btn btn-primary pull-right">Suivant<span class="glyphicon glyphicon-forward"></span></a>
    </div>
    <div id="chartContainer"></div>

</div>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
<script type="text/javascript">
   
    var result1 = @Html.Raw(ViewBag.list);
	var data =[];
	for(var i = 0; i < result1.length; i++){
        data.push({ label: result1[i].prestaName, y: result1[i].MissionsCount});
    }

    window.onload = function () {
        var chart1 = new CanvasJS.Chart("chartContainer", {
            theme: "theme2",
            animationEnabled: true,
            title: {
                text: "Meilleurs Prestataires de ce mois "
            },
            //subtitles: [
            //    { text: "Try Resizing the Browser" }
            //],
            data: [
                {
                    type: "column", //change type to bar, line, area, pie, etc
                    dataPoints: data
                }
            ]
        });
        chart1.render();
  //  };

   // window.onload = function () {
        //    var chart2 = new CanvasJS.Chart("StatesChartContainer", {
        //        title: {
        //            text: "Offre Par Governorat"
        //        },
        //        animationEnabled: true,
        //        legend: {
        //            fontSize: 20,
        //            fontFamily: "Helvetica"
        //        },
        //        theme: "theme2",
        //        data: [
        //        {
        //            type: "doughnut",
        //            indexLabelFontFamily: "Garamond",
        //            indexLabelFontSize: 20,
        //            indexLabel: "{label} {y}%",
        //            startAngle: -20,
        //            showInLegend: true,
        //            toolTipContent: "{legendText} {y}%",
        //            //dataPoints: [
        //            //    { y: 72.48, legendText: "Sousse", label: "Sousse" },
        //            //    { y: 10.39, legendText: "Monastir", label: "Monastir" },
        //            //    { y: 7.78, legendText: "Tunis!", label: "Tunis" },
        //            //    { y: 7.14, legendText: "Kairouan", label: "Kairouan" },
        //            //    { y: 0.22, legendText: "Kasserine", label: "Kasserine" },
        //            //    { y: 0.15, legendText: "Mannouba", label: "Mannouba" },
        //            //    { y: 1.84, legendText: "Ben Arous", label: "Ben Arous" }
        //            //],
        //                dataPoints: dataPoints
                   
        //        }
        //        ]
        //    });
        //chart2.render();




        //var chart3 = new CanvasJS.Chart("PiechartContainer", {
        //    title: {
        //        text: "Offres par Domaines"
        //    },
        //    animationEnabled: true,
        //    legend: {
        //        verticalAlign: "center",
        //        horizontalAlign: "left",
        //        fontSize: 20,
        //        fontFamily: "Helvetica"
        //    },
        //    theme: "theme2",
        //    data: [
        //        {
        //            type: "pie",
        //            indexLabelFontFamily: "Garamond",
        //            indexLabelFontSize: 20,
        //            indexLabel: "{label} {y}%",
        //            startAngle: -20,
        //            showInLegend: true,
        //            toolTipContent: "{legendText} {y}%",
        //            dataPoints: [
        //                { y: 72.48, legendText: "Technologie", label: "Technologie" },
        //                { y: 10.39, legendText: "Médecine", label: "Médecine" },
        //                { y: 7.78, legendText: "Construction", label: "Construction!" },
        //                { y: 7.14, legendText: "Tourisme", label: "Tourisme" },
        //                { y: 0.22, legendText: "Agriculture", label: "Agriculture" },
        //                { y: 0.15, legendText: "Paramédicale", label: "Paramédicale" },
        //                { y: 1.84, legendText: "Autres", label: "Autres" }
        //            ]
        //        }
        //    ]
        //});

      //  chart3.render();
        };
</script>