Contactini/Models/Entities/Domain.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace Contactini.Models.Entities
{
    public class Domain
    {
       
        public int domainId { get; set; }
        [Required]
        [StringLength(maximumLength: 35, ErrorMessage = "Pas plus de 35 caractères")]
        public string Name { get; set; }
        public int MissionCount { get; set; }
        public  string  PhotoLink { get; set; }

       // public virtual Sector sector { get; set; }
        public virtual ICollection<Mission> Missions { get; set; }
        public virtual ICollection<ServiceProvider> ServiceProviders { get; set; }
        public virtual ICollection<Realisation> Realisations { get; set; }

    }
}

Contactini/Controllers/DomainsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Contactini.DAL;
using Contactini.Models.Entities;

namespace Contactini.Controllers
{
    [Authorize(Roles =("Admin"))]
    public class DomainsController : Controller
    {
        private ContactiniContext db = new ContactiniContext();

        // GET: Domains
        public ActionResult Index()
        {
            return View(db.Domains.ToList());
        }

        // GET: Domains/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Domain domain = db.Domains.Find(id);
            if (domain == null)
            {
                return HttpNotFound();
            }
            return View(domain);
        }
        /// <summary>
        /// Domain create in relation with the selected sector
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Domains/Create
        [ChildActionOnly]
        public ActionResult Create(int? id)
        {
            
            
            TempData["ss"] = id;
            return View();
           
        }
       
        // POST: Domains/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
       // [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase upload, Domain domain)
        {
            int id = (int)TempData["ss"];
            Sector ss = db.Sectors.Where(s => s.ID == id).Single();
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    var photo = new Photo
                    {
                        Name = System.IO.Path.GetFileName(upload.FileName),
                        Link = "~/Content/Images/" + upload.FileName,

                    };
                    //   photo.Link = "~/Helpers/" + photo.Name;
                    upload.SaveAs(Server.MapPath(photo.Link));
                    db.Photos.Add(photo);
                    Domain dm = new Domain
                    {
                        Name = domain.Name,
                        PhotoLink = photo.Link
                        
                    };
                    db.Domains.Add(dm);
                    ss.Domain.Add(dm);
                    db.SaveChanges();
                    return RedirectToAction("Index","Sectors", new { id = id });
                }


                return View();
            }

            return View(domain);
        }
        
      
       
        // GET: Domains/Edit/5
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Domain domain = db.Domains.Find(id);
            if (domain == null)
            {
                return HttpNotFound();
            }
            return View(domain);
        }

        // POST: Domains/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Domain domain, HttpPostedFileBase uploadd)
        {
            if (ModelState.IsValid)
            {
                Domain dom = db.Domains.Find(domain.domainId);
                if (uploadd != null && uploadd.ContentLength > 0)
                {
                    var photo = new Photo
                    {
                        Name = System.IO.Path.GetFileName(uploadd.FileName),
                        Link = "~/Content/Images/" + uploadd.FileName,

                    };
                    //   photo.Link = "~/Helpers/" + photo.Name;
                    uploadd.SaveAs(Server.MapPath(photo.Link));
                    db.Photos.Add(photo);
                    dom.PhotoLink = photo.Link;
                  
                }
                dom.Name = domain.Name;
               // int id = db.Sectors.Where(s => s.Domain.Contains(domain)).FirstOrDefault().ID;
               // db.Entry(domain).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Sectors");


            }
            return View(domain);
        }

        // GET: Domains/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Domain domain = db.Domains.Find(id);
            if (domain == null)
            {
                return HttpNotFound();
            }
            return View(domain);
        }

        // POST: Domains/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Domain domain = db.Domains.Find(id);
            db.Domains.Remove(domain);
            db.SaveChanges();
            return RedirectToAction("Index","Sectors");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Contactini/Views/Domains/Create.cshtml
@model Contactini.Models.Entities.Domain
@{
    Layout = "";
}
@using (Html.BeginForm("Create", "Domains", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Nom domaine", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Ajouter Photo", htmlAttributes: new { @class = "control-label col-md-4" })
            <div class="col-md-6">
                <input type="file" id="Photo" name="upload"  onchange="fileCheck(this)" />
                <img src="~/Content/Images/dm.jpg" id="upIm" width="250" height="220" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4"></div>
            <div class="col-md-6">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script>
    function fileCheck(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#upIm').attr('src', e.target.result);
            }

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

Contactini/Views/Domains/Delete.cshtml
@model Contactini.Models.Entities.Domain
@{ 
    Layout = "";
}
<h4>Sure de supprimer cette domaine ?</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Nom du secteur")
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> 
         
        </div>
    }
</div>

Contactini/Views/Domains/Edit.cshtml
@model Contactini.Models.Entities.Domain
@{ 
    Layout = "";
}
@using (Html.BeginForm("Edit", "Domains", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.domainId)

        <div class="form-group">
            @Html.Label("Nom", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Photo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Photo" name="uploadd" onchange="fileCheck(this)" />
                <img src="@Url.Content(String.Format("{0}", Model.PhotoLink))" id="upImed" width="250" height="220"/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enregistrer" class="btn btn-default" />
            </div>
        </div>
    </div>
}
    <script>
        function fileCheck(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#upImed').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }
    </script>