Contactini/Controllers/AdminController.cs
using Contactini.DAL;
using Contactini.Models.Entities;
using IdentitySample.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Contactini.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        // GET: Admin
        public AdminController() { }
        private ContactiniContext db = new ContactiniContext();
        public AdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;

        }
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        //Get connected user profile pic
        public async Task<string> getPicLink()
        {
            string id = User.Identity.GetUserId();
            if (id == null)
            {
                return "Problem Identifying the connected user";
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return "Problem Identifying the connected user";
            }
            string ss = "";
            if (user.PhotoLink != null) ss = user.PhotoLink;
            else ss = "~/Content/Images/Unknown.png";
            return ss;
        }
        /// <summary>
        /// shows List of missions
        /// </summary>
        /// <param name="page"></param>
        /// <param name="pageSize"></param>
        /// <returns></returns>
        // GET: Missions
        [HttpGet]
        public async Task<ActionResult> Index(int page = 1, int pageSize = 4)
        {
            List<SelectListItem> domainList = new List<SelectListItem>();
            List<SelectListItem> sectorList = new List<SelectListItem>();
            List<SelectListItem> stateList = new List<SelectListItem>();
            foreach (var item in db.Domains.ToList()) domainList.Add(new SelectListItem { Text = item.Name, Value = item.Name });
            foreach (var item in db.Sectors.ToList()) sectorList.Add(new SelectListItem { Text = item.Name, Value = item.Name });
            foreach (var item in db.Addresses.ToList()) stateList.Add(new SelectListItem { Text = item.State.ToLower(), Value = item.State });
            ViewBag.Sectors = (IEnumerable<SelectListItem>)sectorList;
            ViewBag.Domains = (IEnumerable<SelectListItem>)domainList;
            ViewBag.States = (IEnumerable<SelectListItem>)stateList.Distinct();

            var list = db.Missions.ToList();
            PagedList<Mission> model = new PagedList<Mission>(list, page, pageSize);
            ViewBag.photoLink = await getPicLink();
            return View(model);
        }
        [HttpPost]
        public async Task<ActionResult> Index(FormCollection form, int page = 1, int pageSize = 4)
        {

            List<SelectListItem> domainList = new List<SelectListItem>();
            List<SelectListItem> sectorList = new List<SelectListItem>();
            List<SelectListItem> stateList = new List<SelectListItem>();
            foreach (var item in db.Domains.ToList()) domainList.Add(new SelectListItem { Text = item.Name, Value = item.Name });
            foreach (var item in db.Sectors.ToList()) sectorList.Add(new SelectListItem { Text = item.Name, Value = item.Name });
            foreach (var item in db.Addresses.ToList()) stateList.Add(new SelectListItem { Text = item.State, Value = item.State });
            ViewBag.Sectors = (IEnumerable<SelectListItem>)sectorList;
            ViewBag.Domains = (IEnumerable<SelectListItem>)domainList;
            ViewBag.States = (IEnumerable<SelectListItem>)stateList;

            string sector = form["Sectors"].ToString();
            string domain = form["Domains"].ToString();
            string state = form["States"].ToString();
            var list = db.Missions.ToList();
            if (sector != "") list = list.Where(l => l.Sector.Name == sector).ToList();
            if (domain != "") list = list.Where(d => d.Domain.Name == domain).ToList();
            if (state != "") list = list.Where(s => s.Address.State == state).ToList();
            PagedList<Mission> model = new PagedList<Mission>(list, page, pageSize);
            if (model == null) ViewBag.message = "aucune résultat !";
            ViewBag.photoLink = await getPicLink();
            return View(model);
        }
        /// <summary>
        /// delete a mission
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult DeleteMission(int id)
        {
            try
            {
                Mission mission = db.Missions.Find(id);
                db.Missions.Remove(mission);
                var cd = db.Candidatures.Where(c => c.Mission.ID == id).ToList();
                foreach (var item in cd) db.Candidatures.Remove(item);
                db.SaveChanges();
                return Content(Boolean.TrueString);
                //return RedirectToAction("Index");
            }
            catch
            {
                return Content(Boolean.FalseString);
            }
        }

        /// <summary>
        /// tells info about the admi space what should he do and how get it done 
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> About()
        {

            ViewBag.photoLink = await getPicLink();
            return View();
        }
        /// <summary>
        /// contact a specific user about some issue
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> Contact()
        {

            ViewBag.photoLink = await getPicLink();
            return View();
        }
    }
}

Contactini/Controllers/myCVController.cs
using Contactini.DAL;
using Contactini.Models;
using Contactini.Models.Entities;
using IdentitySample.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Contactini.Controllers
{
    public class myCVController : Controller
    {
        /// <summary>
        /// controller providing all operations related to the SP cv 
        /// the non commented methods are self explanatory by their name
        /// </summary>
        public myCVController() { }
        private ContactiniContext db = new ContactiniContext();
        public myCVController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        ///Get connected user profile pic
        public async Task<string> getPicLink()
        {
            string id = User.Identity.GetUserId();
            if (id == null)
            {
                return "Problem Identifying the connected user";
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return "Problem Identifying the connected user";
            }
            string ss = "";
            if (user.PhotoLink != null) ss = user.PhotoLink;
            else ss = "~/Content/Images/Unknown.png";
            return ss;
        }
        /// <summary>
        /// show the private version of the connected sp's cv where he could update /delete/add...
        /// </summary>
        /// <returns></returns>
        // GET: myCV
        public async Task<ActionResult> Index()
        {
            ViewBag.photoLink = await getPicLink();
            string id = User.Identity.GetUserId();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            string emailAddress = user.Email;
            Session["email"] = emailAddress;
            ServiceProvider sp = new ServiceProvider();
            sp = db.ServiceProviders.Where(s => s.Email == emailAddress).FirstOrDefault();
            return View(sp);
        }
        /// <summary>
        /// shows the public version of cv so to get printed
        /// </summary>
        /// <param name="email"></param>
        /// <returns></returns>
        public async  Task<ActionResult> Findex(string email)
        {
            ViewBag.photoLink = await getPicLink();
            Session["email"] = email;
            ServiceProvider sp = db.ServiceProviders.Where(s => s.Email == email).FirstOrDefault();
            ViewBag.photoLinkp = sp.photoLink;
            return View(sp);
        }
        [HttpGet]
        [ChildActionOnly]
        public ActionResult Education()
        {
            string email = (string)Session["email"];
            ServiceProvider sp = new ServiceProvider();
            sp = db.ServiceProviders.Where(s => s.Email == email).FirstOrDefault();
            
            return View(sp.Educations);
        }
        [HttpGet]
        [ChildActionOnly]
        public ActionResult EduCV()
        {
            string email = (string)Session["email"];
            ServiceProvider sp = new ServiceProvider();
            sp = db.ServiceProviders.Where(s => s.Email == email).FirstOrDefault();

            return View(sp.Educations);
        }
        [HttpGet]
        public async Task<ActionResult> EduCreate()
        {
            ViewBag.photoLink = await getPicLink();
            return View();
        }
        [HttpPost]
        public ActionResult EduCreate(Education edu)
        {
            if (ModelState.IsValid)
            {
                string email = (string)Session["email"];
                ServiceProvider sp = new ServiceProvider();
                sp = db.ServiceProviders.Where(s => s.Email == email).FirstOrDefault();
                edu.ServiceProvider = sp;
                sp.Educations.Add(edu);
                db.Educations.Add(edu);
                db.SaveChanges();
               return RedirectToAction("Index");
            }
            
            return View(edu);
        }

        [HttpGet]
        public async Task<ActionResult> EduUpdate(int id)
        {
            ViewBag.photoLink = await getPicLink();
            Education edu = db.Educations.Find(id);
            return View(edu);
        }
        [HttpPost]
        public ActionResult EduUpdate(Education edu)
        {
            Education ed = db.Educations.Where(e => e.ID == edu.ID).FirstOrDefault();
            ed.City = edu.City;
            ed.Country = edu.Country;
            ed.Degree = edu.Degree;
            ed.FromYear = edu.FromYear;
            ed.ToYear = edu.ToYear;
            ed.TitleOfDiploma = edu.TitleOfDiploma;
            ed.InstituteUniversity = edu.InstituteUniversity;

            string email = (string)Session["email"];
            ServiceProvider sp = new ServiceProvider();
            sp = db.ServiceProviders.Where(s => s.Email == email).FirstOrDefault();
            Education edd = sp.Educations.Where(e => e.ID == edu.ID).FirstOrDefault();
            edd.City = edu.City;
            edd.Country = edu.Country;
            edd.Degree = edu.Degree;
            edd.FromYear = edu.FromYear;
            edd.ToYear = edu.ToYear;
            edd.TitleOfDiploma = edu.TitleOfDiploma;
            edd.InstituteUniversity = edu.InstituteUniversity;

            db.SaveChanges();
            return RedirectToAction("Index");
        }


     
        public ActionResult EduDelete(int id)
        {
            Education ed = db.Educations.Find(id);
            db.Educations.Remove(ed);
           
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        [ChildActionOnly]
        public ActionResult Experience()
        {
            string email = (string)Session["email"];
            ServiceProvider sp = new ServiceProvider();
            sp = db.ServiceProviders.Where(s => s.Email == email).FirstOrDefault();
            return View(sp.workExperiences);
        }
        [ChildActionOnly]
        public ActionResult ExpCV()
        {
            string email = (string)Session["email"];
            ServiceProvider sp = new ServiceProvider();
            sp = db.ServiceProviders.Where(s => s.Email == email).FirstOrDefault();
            return View(sp.workExperiences);
        }
        [HttpGet]
        public async Task<ActionResult> ExpCreate()
        {
            ViewBag.photoLink = await getPicLink();
            return View();
        }
        [HttpPost]
        public ActionResult ExpCreate(workExperience exp)
        {
            if (ModelState.IsValid)
            {
                string email = (string)Session["email"];
                ServiceProvider sp = new ServiceProvider();
                sp = db.ServiceProviders.Where(s => s.Email == email).FirstOrDefault();
                exp.ServiceProvider = sp;
                sp.workExperiences.Add(exp);
                db.WorkExperiences.Add(exp);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(exp);
        }

        [HttpGet]
        public async Task<ActionResult> ExpUpdate(int id)
        {
            ViewBag.photoLink = await getPicLink();
            workExperience exp = db.WorkExperiences.Find(id);
            return View(exp);
        }
        [HttpPost]
        public ActionResult ExpUpdate(workExperience exp)
        {
            workExperience wp = db.WorkExperiences.Where(w => w.ID == exp.ID).FirstOrDefault();
            wp.Company = exp.Company;
            wp.Country = exp.Country;
            wp.Description = exp.Description;
            wp.FromYear = exp.FromYear;
            wp.ToYear = exp.ToYear;
            wp.Title = exp.Title;


            string email = (string)Session["email"];
            ServiceProvider sp = new ServiceProvider();
            sp = db.ServiceProviders.Where(s => s.Email == email).FirstOrDefault();
            workExperience wx = sp.workExperiences.Where(e => e.ID == exp.ID).FirstOrDefault();
            wx.Company = exp.Company;
            wx.Country = exp.Country;
            wx.Description = exp.Description;
            wx.FromYear = exp.FromYear;
            wx.ToYear = exp.ToYear;
            wx.Title = exp.Title;

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        
        public ActionResult ExpDelete(int id)
        {
            workExperience wp = db.WorkExperiences.Find(id);
            db.WorkExperiences.Remove(wp);
            
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [ChildActionOnly]
        public ActionResult Skills()
        {
            string email = (string)Session["email"];
            ServiceProvider sp = new ServiceProvider();
            sp = db.ServiceProviders.Where(s => s.Email == email).FirstOrDefault();
            return View(sp.Skills);
        }
        [ChildActionOnly]
        public ActionResult SkiCV()
        {
            string email = (string)Session["email"];
            ServiceProvider sp = new ServiceProvider();
            sp = db.ServiceProviders.Where(s => s.Email == email).FirstOrDefault();
            return View(sp.Skills);
        }
        [HttpGet]

Contactini/Views/Shared/AdminLayout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Contactini.tn Application</title>
    @{
        string src = ViewBag.photoLink;
    }
    <style>

        .cent {
            background-color: white;
            margin-top: 15px;
            margin-bottom: 15px;
            padding-bottom: 15px;
        }
    </style>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @*@Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")*@
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</head>
<body style="background-color:dodgerblue;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container ">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Contactini.tn", "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Admin")</li>
                    <li>
                        @Html.ActionLink("Mon profil", "_Edit", "UsersAdmin", new { Id = User.Identity.GetUserId() }, htmlAttributes: new { title = "Manage" })
                    </li>

                    @*<li>@Html.ActionLink("A propos", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Secteurs", "Index", "Sectors")</li>
                    <li>@Html.ActionLink("Roles", "Index", "RolesAdmin")</li>
                    <li>@Html.ActionLink("Utilisateurs", "Index", "UsersAdmin")</li>
                    <li>@Html.ActionLink("Messages", "Index", "UsersAdmin")</li>
                    <li>@Html.ActionLink("Statistique", "Sta1", "UsersAdmin")</li>
                    <li>@Html.ActionLink("Redirect", "Redirect", "Redirect")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content cent">

        @RenderBody()
        <hr />
        <br />
        <div class="row">
            <footer>
                <p>&copy; @DateTime.Now.Year - Contactini.tn</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Contactini/Views/Shared/BusinessLayout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Contactini.tn Application</title>
    @{
        string src = ViewBag.photoLink;
    }
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.js"
            integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>

    <style>
        body {
            background-color: dodgerblue !important;
        }

        .cent {
            background-color: white;
            margin-top: 15px;
            margin-bottom: 15px;
            padding-bottom: 15px;
        }
    </style>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Contactini.tn  App", "Index", "Business", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Business")</li>
                    <li>
                        @Html.ActionLink("Mon profil", "_Edit", "UsersAdmin", new { Id = User.Identity.GetUserId() }, htmlAttributes: new { title = "Manage" })
                    </li>
                    @*<li>@Html.ActionLink("A propos", "About", "Business")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Business")</li>*@
                    <li>@Html.ActionLink("Missions", "Index", "Business")</li>
                    <li>@Html.ActionLink("Mon CV", "Index", "myCV")</li>
                    <li>@Html.ActionLink("Candidatures", "MyApps", "Business")</li>
                    <li>@Html.ActionLink("Mes Favoris", "myFav", "Business")</li>
                    <li>@Html.ActionLink("Redirect", "Redirect", "Redirect")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content cent">
        @RenderBody()
        <hr />
        <div class="row">
            <footer>
                <p>&copy; @DateTime.Now.Year - Contactini.tn</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Contactini/Views/Shared/ContinueAsLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Contactini.tn Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Contactini.tn  App", "Index", "Missions", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <div class="row">
            <footer>
                <p>&copy; @DateTime.Now.Year - Contactini.tn</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Contactini/Views/Shared/ReceptionLayout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Contactini.tn Application</title>
    @{
        string src = ViewBag.photoLink;
    }
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    <script src="https://code.jquery.com/jquery-3.3.1.js"
            integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>
    <style>
        body {
            background-color: dodgerblue;
        }

        .cent {
            background-color: white;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Contactini.tn  App", "Index", "Missions", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Missions")</li>
                    <li>
                        @Html.ActionLink("Mon Profil", "_Edit", "UsersAdmin", new { Id = User.Identity.GetUserId() }, htmlAttributes: new { title = "Manage" })
                    </li>
                    <li>@Html.ActionLink("Validation", "Validations", "Reception")</li>
                    <li>@Html.ActionLink("Prestataires", "Presta", "Missions")</li>
                    <li>@Html.ActionLink("Mes Favoris", "myFav", "Missions")</li>
                    <li>@Html.ActionLink("Redirect", "Redirect", "Redirect")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content cent">
        <div class="row">
            @RenderBody()
        </div>
        <hr />
        <div class="row" align="center">
            <footer>

                <p>&copy; @DateTime.Now.Year - Contactini.tn</p>
            </footer>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Contactini/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Contactini.tn Application</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Contactini.tn", "Index", "Home", null, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                        @*<li>@Html.ActionLink("A propos", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                        <li>@Html.ActionLink("Missions", "MissionsList", "Home")</li>
                        <li>@Html.ActionLink("Prestataires", "prestaList", "Home")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    <div class="container body-content">
        <div class="row">
            @RenderBody()
        </div>
        <hr />

        <div class="row">
            <footer>
                <p>&copy; @DateTime.Now.Year - Contactini.tn</p>
            </footer>
        </div>
    </div>
    

    @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>