Contactini/Controllers/MissionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Contactini.DAL;
using Contactini.Models.Entities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using IdentitySample.Models;
using System.Threading.Tasks;
using PagedList;
using System.Net.Mail;
using Contactini.Models;

namespace Contactini.Controllers
{
    [Authorize]
    public class MissionsController : Controller
    {
        public MissionsController() { }
        private ContactiniContext db = new ContactiniContext();
        public MissionsController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;

        }
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        ///Get connected user profile pic
        public async Task<string> getPicLink()
        {
            string id = User.Identity.GetUserId();
            if (id == null)
            {
                return "Problem Identifying the connected user";
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return "Problem Identifying the connected user";
            }
            string ss = "";
            if (user.PhotoLink != null) ss = user.PhotoLink;
            else ss = "~/Content/Images/Unknown.png";
            return ss;
        }
        /// <summary>
        /// get the list of missions
        /// </summary>
        /// <param name="page"></param>
        /// <param name="pageSize"></param>
        /// <returns></returns>
        // GET: Missions
        [HttpGet]
        public async Task<ActionResult> Index(int page = 1, int pageSize = 4)
        {
            List<SelectListItem> domainList = new List<SelectListItem>();
            List<SelectListItem> sectorList = new List<SelectListItem>();
            List<SelectListItem> stateList = new List<SelectListItem>();
            foreach (var item in db.Domains.ToList()) domainList.Add(new SelectListItem { Text = item.Name, Value = item.Name });
            foreach (var item in db.Sectors.ToList()) sectorList.Add(new SelectListItem { Text = item.Name, Value = item.Name });
            foreach (var item in db.Addresses.ToList()) //stateList.Add(new SelectListItem { Text = item.State.ToLower().Trim(), Value = item.State });

            {
                var bla = new SelectListItem { Text = item.State.ToLower().Trim(), Value = item.State.ToLower().Trim() };
                if (!stateList.Exists(elem=>elem.Text==bla.Text&&elem.Value==bla.Value))
                stateList.Add(bla);
            }
                //stateList.Add(new SelectListItem { Text = item.State.ToLower().Trim() , Value = item.State });
            ViewBag.Sectors = (IEnumerable<SelectListItem>)sectorList;
            ViewBag.Domains = (IEnumerable<SelectListItem>)domainList;
            ViewBag.States = (IEnumerable<SelectListItem>)stateList;

            var list = db.Missions.ToList();
            PagedList<Mission> model = new PagedList<Mission>(list, page, pageSize);
            ViewBag.photoLink = await getPicLink();
            return View(model);
        }
        /// <summary>
        /// get the list of missions result of the research
        /// </summary>
        /// <param name="form"></param>
        /// <param name="page"></param>
        /// <param name="pageSize"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<ActionResult> Index(FormCollection form, int page = 1, int pageSize = 4)
        {

            List<SelectListItem> domainList = new List<SelectListItem>();
            List<SelectListItem> sectorList = new List<SelectListItem>();
            List<SelectListItem> stateList = new List<SelectListItem>();
            foreach (var item in db.Domains.ToList()) domainList.Add(new SelectListItem { Text = item.Name, Value = item.Name });
            foreach (var item in db.Sectors.ToList()) sectorList.Add(new SelectListItem { Text = item.Name, Value = item.Name });
            foreach (var item in db.Addresses.ToList())// stateList.Add(new SelectListItem { Text = item.State, Value = item.State });
            {
                var bla = new SelectListItem { Text = item.State.ToLower().Trim(), Value = item.State.ToLower().Trim() };
                if (!stateList.Exists(elem => elem.Text == bla.Text && elem.Value == bla.Value))
                    stateList.Add(bla);
            }
            ViewBag.Sectors = (IEnumerable<SelectListItem>)sectorList;
            ViewBag.Domains = (IEnumerable<SelectListItem>)domainList;
            ViewBag.States = (IEnumerable<SelectListItem>)stateList;

            string sector = form["Sectors"].ToString();
            string domain = form["Domains"].ToString();
            string state = form["States"].ToString();
            var list = db.Missions.ToList();
            if (sector != "") list = list.Where(l => l.Sector.Name == sector).ToList();
            if (domain != "") list = list.Where(d => d.Domain.Name == domain).ToList();
            if (state != "") list = list.Where(s => s.Address.State.ToLower().Trim() == state).ToList();
            PagedList<Mission> model = new PagedList<Mission>(list, page, pageSize);
            if (model == null) ViewBag.message = "aucune résultat !";
            ViewBag.photoLink = await getPicLink();
            return View(model);
        }

        /// <summary>
        /// shows the details of a mission
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        // GET: Missions/Details/5
        public ActionResult Details(int? id)
        {
            if (Request.IsAjaxRequest())
            {

           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mission mission = db.Missions.Find(id);
            if (mission == null)
            {
                return HttpNotFound();
            }
            return PartialView(mission);
            }
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
        /// <summary>
        /// Add a new mission/new Offer
        /// </summary>
        /// <returns></returns>
        // GET: Missions/Create
        public async    Task<ActionResult> Create()
        {
            List<SelectListItem> domainList = new List<SelectListItem>();
            List<SelectListItem> sectorList = new List<SelectListItem>();
            foreach (var item in db.Domains.ToList()) domainList.Add(new SelectListItem {Text=item.Name,Value=item.Name });
            foreach (var item in db.Sectors.ToList()) sectorList.Add(new SelectListItem { Text = item.Name, Value = item.Name });
            ViewBag.Sectors =  (IEnumerable<SelectListItem>)sectorList;
            ViewBag.Domains = (IEnumerable<SelectListItem>)domainList;
            string ss= await getPicLink();
            ViewBag.photoLink = ss;
            return View();
        }

        // POST: Missions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create( Mission mission,FormCollection form, HttpPostedFileBase upload)
        {
            //if (ModelState.IsValid)
            //{
            //try { 
                if (upload != null && upload.ContentLength > 0)
                {
                    var photo = new Photo
                    {
                        Name = System.IO.Path.GetFileName(upload.FileName),
                        Link = "~/Content/Images/" + upload.FileName,

                    };
                    //   photo.Link = "~/Helpers/" + photo.Name;
                    upload.SaveAs(Server.MapPath(photo.Link));
                    db.Photos.Add(photo);
                    mission.PhotoLink = photo.Link;
                }
                else
                {
                    mission.PhotoLink = "~/Content/Images/jobOffer.jpg";
                }
                Address ad = mission.Address;
                db.Addresses.Add(ad);
                //Finding the client who posted this mission , so to add this mission to his list of propopsitions
                string id = User.Identity.GetUserId();
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                string emailAddress = user.Email;
                Client cust = new Client();
                cust = db.Clients.Where(x => x.Email == emailAddress).FirstOrDefault();
                if (cust == null)
                {
                    // return HttpNotFound();

Contactini/Views/Admin/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"><h2>Page a propos </h2></div>
    <div class="panel-body">
        <p>
            Dan cette Page on affiche des informatioons a propos du notre application mais seulement sur la coté client <br />
            genre tous ce qu'il peut utiliser , comment utiliser , comment reporter ne probleme, et les nouveau mise a jour de l'application
        </p>
    </div>


</div>

Contactini/Views/Admin/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"><h2>Page du contact </h2></div>
    <div class="panel-body">
        <p>
            La page ou le client peut contacter les administrateurs plus facilement
        </p>
    </div>


</div>

Contactini/Views/Admin/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList<Mission>
@using Contactini.Models.Entities
@using Contactini.Models
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<style>
    .cent {
        background-color: white;
        margin-top: 15px;
        margin-bottom: 15px;
        padding-bottom: 15px;
    }
</style>
<h2 class="alert alert-info text-center">Nouveaux Missions</h2>
<p align="center">
    @*@Html.ActionLink("Nouvel Offre", "Create", null, new { @class = "btn btn-primary glyphicon glyphicon-plus" })*@
    @*@Html.ActionLink("Mes Missions", "MyMissions", null, new { @class = "btn btn-primary glyphicon glyphicon-plus" })*@
</p>
<div class="container">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div style="margin-right:10px;">

            <div class="form-horizontal" style="margin-bottom:5px;margin-top:5px;margin-right:5px;margin-left:5px;" align="center">
                <div class="row">
                    <div class="col-md-3">
                        @Html.DropDownList("Sectors", (IEnumerable<SelectListItem>)ViewBag.Sectors, "Choisir un secteur", htmlAttributes: new { @class = "form-control control-label" })
                    </div>



                    <div class="col-md-3">
                        @Html.DropDownList("Domains", (IEnumerable<SelectListItem>)ViewBag.Domains, "Choisir un domaine", htmlAttributes: new { @class = "form-control control-label" })
                    </div>

                    <div class="col-md-3">
                        @Html.DropDownList("States", (IEnumerable<SelectListItem>)ViewBag.States, "Choisir une governorat", htmlAttributes: new { @class = "form-control control-label" })
                    </div>

                    <div class="col-md-3">
                        <input type="submit" value="Sélection" class="btn btn-default" />
                        <a href="@Url.Action("Index","Missions")" class="btn btn-primary">Annuler</a>
                    </div>
                </div>
            </div>
        </div>
    }
    @foreach (var item in Model)
    {
        <div class="col-md-6">
            <div class="card text-center">
                <div class="card-header" style="background-color:@(item.State == Status.Ouverte ? "dodgerblue":"grey")">
                    <h5 style="color:white;">
                        Secteur : @Html.DisplayFor(modelItem => item.Sector.Name) | Domaine : @Html.DisplayFor(modelItem => item.Domain.Name)
                    </h5>
                </div>
                <div class="card-body" align="center">
                    <div>
                        <h5 class="card-title well well-sm" style="width:50%;color:white; background-color:dodgerblue;">@Html.DisplayFor(modelItem => item.Title)</h5>
                    </div>
                    <div style=" margin-left:25px; margin-right:25px;">
                        <table class="table table-bordered">
                            <tr class="thead-default">
                                <th class="text-center">Date publication</th>
                                <th class="text-center">Date début</th>
                                <th class="text-center">Durée</th>
                                <th class="text-center">Situation</th>
                            </tr>
                            <tr>
                                <th class="text-center">@Html.DisplayFor(modelItem => item.PublishDate)</th>
                                <th class="text-center">@Html.DisplayFor(modelItem => item.StartDate)</th>
                                <th class="text-center">@Html.DisplayFor(modelItem => item.Duration)</th>
                                <th class="text-center">@Html.DisplayFor(modelItem => item.State)</th>
                            </tr>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div>@Html.Image(@Url.Content(item.PhotoLink), "Job Offer", "190", "250")</div>
                        </div>
                        <div class="col-md-6">
                            <p class="card-text  pull-left" style="width:250px ;height:180px ;text-overflow:ellipsis; overflow:hidden; margin-bottom:3px;">@Html.DisplayFor(modelItem => item.Description).</p>
                        </div>
                    </div>

                </div>
                <div class="card-footer text-muted">
                    <div class="row center-block">
                        <button type="button" class="btn btn-warning" data-target="#myModal1" data-toggle="modal" onclick="confirmDelete(@item.ID)">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                            Supprimer
                        </button>
                        <a class="btn btn-primary" data-target="#myModal2" data-toggle="modal" id="@item.ID" onclick="Contactclient(this.id)"><span class="glyphicon glyphicon-envelope"></span>Contact</a>
                        <a href="#" class="btn btn-primary" data-target="#myModal" data-toggle="modal" id="@item.ID" onclick="Details(this.id)"><span class="glyphicon glyphicon-sunglasses"></span>Détails</a>
                    </div>
                </div>
            </div>
        </div>

    }
</div>
<div>
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    <div class="alert alert-info">
        Affichage @Model.FirstItemOnPage à @Model.LastItemOnPage de @Model.TotalItemCount Missions
    </div>
</div>
<input type="hidden" id="hiddenMissionId" />
<div class="modal" id="myModal1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" data-dismiss="modal">&times;</button>
                <h4>Supprimer la mission</h4>
            </div>
            <div class="modal-body">
                Confirmer la suppression de cette mission
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">fermer</a>
                <a href="#" class="btn btn-default" onclick="DeleteMission()">Supprimer</a>
                @*<input type="reset" value="Delete" class="btn-success" id="btnSubmit" />*@
            </div>
        </div>
    </div>
</div>
<div class="modal" id="myModal" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" data-dismiss="modal">&times;</button>
                <h4 class="well text-center">Details du Mission </h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">Fermer</a>
            </div>
        </div>
    </div>
</div>
<div class="modal" id="myModal2" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" data-dismiss="modal">&times;</button>
                <h4>Contacter Le Client :</h4>
            </div>
            <div class="modal-body contender1">
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">Annuler</a>
            </div>
        </div>
    </div>
</div>
<div class="modal" id="myModal3" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close" data-dismiss="modal">&times;</button>
                <h4>Envoi du Message</h4>
            </div>
            <div class="modal-body contender2">

            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">Close</a>
            </div>
        </div>
    </div>
</div>
<script>
    function Details(id) {
        $.get("@Url.Action("Details","Missions")/" + id,
            function (data) { $('.modal-body').html(data); })
    }
    function Contactclient(id) {
        $.get("@Url.Action("contactClient","Missions")/" + id,
            function (data) { $('.contender1').html(data); })
    }
      var confirmDelete = function (ID) {
        $("#hiddenMissionId").val(ID);
    }

    var DeleteMission = function () {
        var Id = $("#hiddenMissionId").val();

        $.ajax({

            type: "POST",
            url: '/Admin/DeleteMission',
            data: JSON.stringify({ 'id': Id }),
            contentType: "application/json; charset=utf-8",
            success: function (result) {
                $("#myModal1").modal("hide");
                $('.card').closest().remove();
                location.reload();
            } 

        })

    }
</script>